name: "CI Workflow Code Quality"
on: 
  workflow_call:
    inputs:
      code_quality_check_command: 
        required: true
        type: string
jobs:

  linters:
    name: Code Quality checks
    runs-on: ubuntu-20.04
    env:
      PYTHONUNBUFFERED: 1
    steps:
      - name: Decide Python Version
        run: |
          if [[ '${{ github.event.pull_request.base.ref }}' == '15.0'* ]]; then
            echo "PY_VERSION=3.7" >> $GITHUB_ENV
            echo "The Python version to be used is 3.7"
          elif [[ '${{ github.event.pull_request.base.ref }}' == '14.0'* ]]; then
            echo "PY_VERSION=3.6" >> $GITHUB_ENV
            echo "The Python version to be used is 3.6"
          else
            echo "PY_VERSION=3.5" >> $GITHUB_ENV
            echo "The Python version to be used is 3.5"
          fi;
      - name: Install Python
        uses: actions/setup-python@v4
        id: python
        with:
          python-version: ${{ env.PY_VERSION }}
          cache: 'pip'
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.ACTIONS_READ_TOKEN }}
          path: main
      - name: Checkout BT-CLI
        uses: actions/checkout@v2
        with:
          ref: master
          token: ${{ secrets.ACTIONS_READ_TOKEN }}
          repository: brain-tec/bt-docker.git
          path: 'bt-docker'      
      - name: Install BT-CLI
        run: 'pip install -I ./bt-docker'
      - name: Login to Registry
        run: 'echo "${{ secrets.BT_REGISTRY_PASSWORD }}" | docker login registry.braintec-group.com -u "${{ secrets.BT_REGISTRY_USERNAME }}" --password-stdin'
      - name: Getting Pylint
        run: 'docker pull registry.braintec-group.com/bt-pylint:${{ env.PY_VERSION }}'
      - name: Check BT CLI installation
        run: 'bt --version'
      - name: Run Code Quality checks
        run: |
          cd main
          ${{ inputs.code_quality_check_command }}
  
